### ISSUE TITLE
Coding issue SOS

### ISSUE THREAD

**Issue by qwert-asdfg** [Date-Science-Talents/Data_Present#10]
The following error occurred when analyzing the use characteristics of LinkTiltle of users of different genders, but the same calculation method is applicable to the analysis of LinkType. 
![17371606397660_ pic_hd](https://user-images.githubusercontent.com/74863947/100398904-96294e00-3048-11eb-8a1a-f7f2b547f8ae.jpg)
![17391606397854_ pic_hd](https://user-images.githubusercontent.com/74863947/100398906-99bcd500-3048-11eb-8eae-63df14ca8528.jpg)

**Comment by deemoren** [comment]
You can not merge string to timestamp. Try to set the timestamp data as the index
