### ISSUE TITLE
Who has the whole cleaned data with tags for LinkType?

### ISSUE THREAD

**Issue by Clipboooard** [Date-Science-Talents/Data_Present#11]
I saw a version of CSV file contains the tags for disabled and non-disabled people. But the value of time for disabled people seems to disappear.
Any body has the whole tagged data set?
![image](https://user-images.githubusercontent.com/57746153/100650595-12b77780-333c-11eb-87c4-befd44874a7a.png)

**Comment by qwert-asdfg** [comment]
Here is the file with fixed time format [1.xlsx](https://github.com/Date-Science-Talents/Data_Present/files/5630495/1.xlsx)
