### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by derekli480796** [Date-Science-Talents/Data_Present#13]
![Screen Shot 2020-12-03 at 4 13 51 PM](https://user-images.githubusercontent.com/25750917/101057067-89928180-3583-11eb-9ff6-6e5b13463c27.png)

Hey guy, I got this heatmap here for correlation between different activities. But it doesn't seem right. Do you know which part is wrong? Let me know if you need more info.

**Comment by deemoren** [comment]
Hi, what your design is asymmetrical heat map. Try to change the coordinates of the X-axis or Y-axis. You can explore the relationship between activity and time, the relationship between activity and disability type, etc.
