### ISSUE TITLE
Does anyone know what those locations are?

### ISSUE THREAD

**Issue by deemoren** [Date-Science-Talents/Data_Present#14]

**Comment by deemoren** [comment]
![image](https://user-images.githubusercontent.com/62387733/101057511-045b9c80-3584-11eb-9541-e7700fa1f819.png)

**Comment by deemoren** [comment]
You can see some erratic values in the location of housings, like East, West, WEST HOUSING, NORTH HOUSING , and South. Do you know what are they?



I know that we can ignore the test machines according to the comment from ColinF.

**Comment by SidAishan** [comment]
I am also processing this data frame according to the location now and have some problem in the unit cell 'Regional location'.

**Comment by SidAishan** [comment]
> You can see some erratic values in the location of housings, like East, West, WEST HOUSING, NORTH HOUSING , and South. Do you know what are they?
> 
> I know that we can ignore the test machines according to the comment from ColinF.

Valuable info from the data holder, get it.
