### ISSUE TITLE
How to display thousands of data clearly in one graph?

### ISSUE THREAD

**Issue by deemoren** [Date-Science-Talents/Data_Present#15]
I have some trouble while trying to present the relationship between the type of activities and activities: there are over 1400 kinds of activities and I can not show them clearly on one screen.

![image](https://user-images.githubusercontent.com/62387733/101058179-c57a1680-3584-11eb-8309-c4a68e7c520e.png)

The data is so overwhelming!

**Comment by SidAishan** [comment]
Does it make sense to aggregate some types which have fewer samples as an integration?
Btw, overwhelming yet beautiful and energetic

**Comment by derekli480796** [comment]
I think in this situation, it's not necessary to show all of the activities. If a single activities' usage frequency is smaller than a specific amount, for example, activities that have only been visited once in the past two years, do not really have influences on the usage of other activities. 
It probably better to only show a few of the important and top-visited ones.

**Comment by deemoren** [comment]
Thank you all
