### ISSUE TITLE
About using coordinate and map to visualise location data

### ISSUE THREAD

**Issue by SidAishan** [Date-Science-Talents/Data_Present#16]
Hi, peers!

I am trying to calculate and show page view(PV) and user view(UV) as bars to a map. I have tried Flourish, but it does not support that as expected. Do you guys have any experience or ideas to create that kind of visualisation?

**Comment by SidAishan** [comment]
![image](https://user-images.githubusercontent.com/43022856/101059732-90dc7e00-35c9-11eb-983c-b60650cee5ef.png)
I try to use an open-source repository to create the visualisation as above. While the code is based on javascript, I lack in experience in coding js. I am not sure I could do much personalisation to the result and I will have a try.

**Comment by deemoren** [comment]
You have done an excellent job! Besides, I recommend you use excel to draw the picture, which is much smarter. 
![image](https://user-images.githubusercontent.com/62387733/101182308-d0e14680-3645-11eb-8422-0132a04aae26.png)

**Comment by deemoren** [comment]
You have done an excellent job! Besides, I recommend you use excel to draw the picture, which is much smarter.
Here I random some data and try to show them on a 3D map:

![image](https://user-images.githubusercontent.com/62387733/101182484-1140c480-3646-11eb-944b-cbddee9f5096.png)

**Comment by Clipboooard** [comment]
Hi! The pic looks great! Maybe you can try FOLIUM if you still wanna use python to finish it? Here's a link to it:https://github.com/gaonanlee/Visualization-Practice/blob/master/Folium%20Visualization%20Examples.ipynb
And also the instructions here: https://python-visualization.github.io/folium/quickstart.html
I don't know if this could contributes to your visualization, at least you can try!
