### ISSUE TITLE
How to use github on mobile phone?

### ISSUE THREAD

**Issue by deemoren** [Date-Science-Talents/Data_Present#18]
Do yo know how to upload files from iPad or mobile phone to GitHub?

**Comment by SidAishan** [comment]
I know an app from the ios app store named 'Working Copy - Git client'. It could connect to Github and clone repository like my screenshot below. Hope that helps!
![image](https://user-images.githubusercontent.com/43022856/101275738-096a5700-37e3-11eb-89ff-94899dd4fd9a.png)

**Comment by SidAishan** [comment]
The above would help you manage your repository from the smartphone. I will close this question :)
