### ISSUE TITLE
Question about choosing a proper way to illustrate data

### ISSUE THREAD

**Issue by Clipboooard** [Date-Science-Talents/Data_Present#7]
Hey guys, I just got the result of my part of processing here:

Every single new user use the platform 4.5 times  each day.
Every single old user use the platform 6.6 times each day.

Since there are only two numbers, I'm quite confused about how to present this relation vividly. Do you have any suggestion on what kinda charts may I use? Thx a lot!

**Comment by qwert-asdfg** [comment]
To compare the frequency or size of different items of the same type, I think you could try the left/right correlation composite bar chart or stacked bar chart.

**Comment by qwert-asdfg** [comment]
To compare the frequency or size of different items of the same type, I think you could try the left/right correlation composite bar chart or stacked bar chart.

**Comment by qwert-asdfg** [comment]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/74863947/100393401-6ae73480-3031-11eb-9df1-8e4abc14cc48.png">

**Comment by qwert-asdfg** [comment]
To compare the frequency or size of different items of the same type, I think you could try the left/right correlation composite bar chart or stacked bar chart.

**Comment by Clipboooard** [comment]
> To compare the frequency or size of different items of the same type, I think you could try the left/right correlation composite bar chart or stacked bar chart.

cool, I'll try that

**Comment by derekli480796** [comment]
If there are only two data, I think a pie chart would be a good way to show it.

**Comment by derekli480796** [comment]
If there are only two data, I think a pie chart would be a good way to show it.
